service: reto-zoluxiones
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: 
        - arn:aws:dynamodb:us-west-1:375466748597:table/PeopleTable

functions:
  swapi_getPeople:
    handler: src/swapi/getPeople.getPeople
    events:
      - httpApi:
          path: /swapi/people
          method: get
  swapi_getPlanets:
    handler: src/swapi/getPlanets.getPlanets
    events:
      - httpApi:
          path: /swapi/planets
          method: get

  addPeople:
    handler: src/people/addPeople.addPerson
    events:
      - httpApi:
          path: /people
          method: post
  getPeople:
    handler: src/people/getPeople.getPeople
    events:
      - httpApi:
          path: /people
          method: get
  getPerson:
    handler: src/people/getPerson.getPerson
    events:
      - httpApi:
          path: /people/{id}
          method: get

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeopleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
