service: reto-zoluxiones
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: 
        - arn:aws:dynamodb:us-west-1:375466748597:table/PeopleTable

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeopleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
