swagger: "2.0"
info:
  description: "Reto-Zoluxiones"
  version: "1.0.0"
  title: "Reto-Zoluxiones"

tags:
- name: "swapi"
  description: "Consultas al api de Swapi"
- name: "people"
  description: "Consultas para registro y listado de personas"
schemes:
- "http"
paths:
  /swapi/people:
    get:
      tags:
      - "swapi"
      summary: "lista personajes de Swapi"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        
          
  /swapi/planets:
    get:
      tags:
      - "swapi"
      summary: "lista planetas de Swapi"
      operationId: "listUser"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
  /people:
    post:
      tags:
      - "people"
      summary: "Registrar persona"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "usuario creado"
        required: true
        schema:
          $ref: "#/definitions/Person"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
    
    get:
      tags:
      - "people"
      summary: "Listar personas registradas"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"

  /people/{id}:
    get:
      tags:
      - "people"
      summary: "Obtener datos de persona por id"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        type: "string"
        required: true
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"

definitions:
  Person:
    type: "object"
    properties:
      id:
        type: "string"
      nombre:
        type: "string"
      genero:
        type: "string"
      planetaOrigen:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      error:
        type: "boolean"
      message:
        type: "string"
      data:
        type: "object"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"